const {chromium}=require('playwright');
const {pathToFileURL}=require('url');
const path=require('path'),fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({acceptDownloads:true});const errors=[],requests=[];
 page.on('pageerror',e=>errors.push(String(e)));
 page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
 const out=path.resolve('.local/site-test-review');fs.mkdirSync(out,{recursive:true});
 await page.goto(process.argv[2]||pathToFileURL(path.resolve('kooperation/START_HIER.html')).href);
 if(await page.locator('#siteCode').count()!==1)throw Error('Form not initialized');
 if(await page.locator('#reviewed,#reportKind,#reportExportedAt,#preflightFile,#reportFile,#textDownload,#printForm').count())throw Error('Removed controls remain');
 for(const [name,width,height] of [['desktop',1280,900],['mobile',390,844]]){
  await page.setViewportSize({width,height});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow '+name);
  await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});
 }
 await page.locator('#server').fill('https://reportserver.example.invalid/ReportServer');
 await page.locator('#catalog').fill('/QM/ARIA18_Throughput_Collector_2.0');
 await page.locator('#linkForm button').click();
 if(await page.locator('#execute').isVisible())throw Error('Placeholder may not execute');
 await page.locator('#server').fill('https://example.test/ReportServer');
 await page.locator('#catalog').fill('/QM und Test/ARIA18_Throughput_Collector_2.0');
 await page.locator('#linkForm button').click();
 const url=new URL(await page.locator('#execute').getAttribute('href'));
 if(url.searchParams.has('IncludePseudonymizedDetails')||url.searchParams.has('DataThroughConfirmed')||url.searchParams.get('rs:Format')!=='EXCELOPENXML'||url.searchParams.get('PeriodEnd')!=='2025-12-31'||!url.search.includes('QM%20und%20Test'))throw Error('Incorrect URL');
 await page.locator('#server').fill('javascript:alert(1)');
 if(await page.locator('#execute').isVisible())throw Error('Stale execute link after edit');
 await page.locator('#siteCode').fill('TEST-STR');
 const downloadPromise=page.waitForEvent('download');
 await page.locator('#siteForm button[type=submit]').click();
 const download=await downloadPromise;
 const expected='TEST-STR_Standorttest_20250101-20251231_R01_Standortformular.json';
 if(download.suggestedFilename()!==expected)throw Error('Submission filename');
 const jsonPath=path.join(out,expected);await download.saveAs(jsonPath);
 const data=JSON.parse(fs.readFileSync(jsonPath,'utf8'));
 if(data.files.length!==2||data.schema_version!=='cooperation-2'||JSON.stringify(data).includes('example.test')||Object.hasOwn(data.values,'server'))throw Error('Submission contents');
 if(await page.locator('#siteForm button').count()!==1)throw Error('Expected one JSON command');
 if(!data.values.reportFile||!data.files[0].endsWith('_FullCollector.xlsx'))throw Error('Excel is required alongside JSON');
 for(const id of ['patients2025','patientCountBasis2025','patientCountSource2025']){
  if(await page.locator('#'+id).getAttribute('required')!==null)throw Error('Benchmark must remain optional');
 }
 if(data.values.patients2025!=='')throw Error('Unknown patient count must not default to zero');
 await page.locator('#patients2025').fill('2500');
 await page.locator('#patientCountBasis2025').selectOption('unique_all');
 await page.locator('#patientCountSource2025').fill('Synthetischer Jahresbericht; inkl. Brachy/Tomo');
 const benchmarkPromise=page.waitForEvent('download');await page.locator('#siteForm button[type=submit]').click();
 const benchmarkPath=path.join(out,'benchmark.json');await (await benchmarkPromise).saveAs(benchmarkPath);
 const benchmark=JSON.parse(fs.readFileSync(benchmarkPath,'utf8'));
 if(benchmark.values.patients2025!=='2500'||benchmark.values.patientCountBasis2025!=='unique_all')throw Error('Benchmark export');
 await page.locator('#patients2025').fill('-1');
 if(await page.locator('#patients2025').evaluate(e=>e.checkValidity()))throw Error('Negative count accepted');
 await page.locator('#patients2025').fill('1.5');
 if(await page.locator('#patients2025').evaluate(e=>e.checkValidity()))throw Error('Fractional count accepted');
 await page.locator('#patients2025').fill('0');
 if(!(await page.locator('#patients2025').evaluate(e=>e.checkValidity())))throw Error('Explicit zero rejected');
 await page.locator('#resume').setInputFiles(benchmarkPath);
 await page.waitForFunction(()=>document.getElementById('patients2025').value==='2500');
 const legacy={...data,values:{...data.values}};
 for(const id of ['patients2025','patientCountBasis2025','patientCountSource2025'])delete legacy.values[id];
 await page.locator('#resume').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});
 await page.waitForFunction(()=>document.getElementById('patients2025').value==='');
 if(await page.locator('#patientCountBasis2025').inputValue()!=='unknown')throw Error('Stale benchmark after legacy import');
 await page.locator('#revision').fill('2');await page.locator('#replaces').fill(data.submission_id);
 const revisionPromise=page.waitForEvent('download');await page.locator('#siteForm button[type=submit]').click();
 if((await revisionPromise).suggestedFilename()!==expected.replace('_R01_','_R02_'))throw Error('Revision filename');
 await page.locator('#resume').setInputFiles(jsonPath);
 await page.waitForFunction(()=>document.getElementById('revision').value==='1');
 if(!(await page.locator('#fileNames').innerText()).includes('_FullCollector.xlsx'))throw Error('Roundtrip file pair');
 await page.locator('#resume').setInputFiles({name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...data,schema_version:'cooperation-1'}))});
 await page.waitForFunction(()=>document.getElementById('formMessage').textContent.includes('mit Ereignisdetails'));
 await page.locator('#resume').setInputFiles({name:'profile.json',mimeType:'application/json',buffer:Buffer.from('{"machines":{},"activity_codes":{}}')});
 await page.waitForFunction(()=>document.getElementById('formMessage').textContent.includes('Kein gueltiges'));
 await browser.close();
 if(errors.length)throw Error(errors.join('\n'));
 if(!(process.argv[2]||'').startsWith('http')&&requests.length)throw Error('Unexpected network request');
 console.log('SITE_TEST_BROWSER_OK desktop/mobile offline JSON-only import Excel-pair editable-only URL');
})().catch(e=>{console.error(e);process.exit(1)});
