const {chromium}=require('playwright');
const {pathToFileURL}=require('url');
const path=require('path'),fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({acceptDownloads:true});const errors=[],requests=[];
 page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
 const out=path.resolve('.local/site-test-review');fs.mkdirSync(out,{recursive:true});
 await page.goto(process.argv[2]||pathToFileURL(path.resolve('kooperation/START_HIER.html')).href);
 if(await page.locator('#siteCode').count()!==1)throw Error('Form not initialized');
 for(const [name,width,height] of [['desktop',1280,900],['mobile',390,844]]){
  await page.setViewportSize({width,height});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow '+name);
  await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});
 }
 await page.locator('#server').fill('https://reportserver.example.invalid/ReportServer');
 await page.locator('#catalog').fill('/QM/ARIA18_Throughput_Collector_2.0');
 await page.locator('#linkForm button').click();
 if(await page.locator('#execute').isVisible())throw Error('Placeholder may not execute');
 await page.locator('#server').fill('https://example.test/ReportServer');
 await page.locator('#catalog').fill('/QM und Test/ARIA18_Throughput_Collector_2.0');
 await page.locator('#linkForm button').click();
 const url=new URL(await page.locator('#execute').getAttribute('href'));
 if(url.searchParams.get('IncludePseudonymizedDetails')!=='0'||url.searchParams.get('DataThroughConfirmed')!=='0'||url.searchParams.get('rs:Format')!=='EXCELOPENXML'||url.searchParams.get('PeriodEnd')!=='2025-12-31'||!url.search.includes('QM%20und%20Test'))throw Error('Unsafe or incorrect URL');
 await page.locator('#server').fill('javascript:alert(1)');
 if(await page.locator('#execute').isVisible())throw Error('Stale execute link after edit');
 await page.locator('#reportKind').selectOption('preflight');
 if(await page.locator('#urlEnd').inputValue()!=='2025-02-28')throw Error('Preflight period');
 await page.locator('#siteCode').fill('TEST-STR');await page.locator('#institution').fill('Synthetic site');
 await page.locator('#contact').fill('Test coordination');await page.locator('#email').fill('test@example.invalid');
 await page.locator('#reportStatus').selectOption('done');await page.locator('#preflightStatus').selectOption('partial');
 await page.locator('#reportFile').check();await page.locator('#preflightFile').check();
 await page.locator('#siteForm button').click();
 if(await page.locator('#reviewed').evaluate(el=>el.validity.valid))throw Error('Local review should be required');
 await page.locator('#reviewed').check();await page.locator('#siteForm button').click();
 if(!(await page.locator('#formMessage').innerText()).includes('Exportzeit'))throw Error('Missing export timestamp accepted');
 await page.locator('#reportExportedAt').fill('2026-09-15T12:00');await page.locator('#preflightExportedAt').fill('2026-09-15T11:55');
 const downloadPromise=page.waitForEvent('download');await page.locator('#siteForm button').click();const download=await downloadPromise;
 const expected='TEST-STR_Standorttest_20250101-20251231_R01_Standortformular.json';
 if(download.suggestedFilename()!==expected)throw Error('Submission filename');
 const jsonPath=path.join(out,expected);await download.saveAs(jsonPath);const data=JSON.parse(fs.readFileSync(jsonPath,'utf8'));
 if(data.files.length!==3||data.schema_version!=='cooperation-1'||JSON.stringify(data).includes('example.test')||Object.hasOwn(data.values,'server'))throw Error('Submission contents');
 await page.locator('#revision').fill('2');await page.locator('#siteForm button').click();
 if(!(await page.locator('#formMessage').innerText()).includes('Vorherige'))throw Error('Replacement identity not required');
 await page.locator('#replaces').fill(data.submission_id);await page.locator('#changeReason').fill('Synthetic revision test');
 const revisionPromise=page.waitForEvent('download');await page.locator('#siteForm button').click();
 if((await revisionPromise).suggestedFilename()!==expected.replace('_R01_','_R02_'))throw Error('Revision filename');
 await page.locator('#resume').setInputFiles(jsonPath);await page.waitForFunction(()=>document.getElementById('revision').value==='1');
 if(await page.locator('#reviewed').isChecked())throw Error('Imported review must reset');
 await page.locator('#resume').setInputFiles({name:'profile.json',mimeType:'application/json',buffer:Buffer.from('{"machines":{},"activity_codes":{}}')});
 await page.waitForFunction(()=>document.getElementById('formMessage').textContent.includes('Kein gueltiges'));
 await browser.close();if(errors.length)throw Error(errors.join('\n'));
 if(!(process.argv[2]||'').startsWith('http')&&requests.length)throw Error('Unexpected network request');
 console.log('SITE_TEST_BROWSER_OK desktop/mobile offline form validation export import safe URL');
})().catch(e=>{console.error(e);process.exit(1)});
